export const BUILTIN_LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuszDhfiJzwrKtpFdQvzA
ZyVmEErmQW+asHHw+UU2844TfQRZ+GXsFkZl4x/Zk3M+uIvRRphoGktFvpSsp+sB
53zxxalivHOhgLX7mwuRosIppDTf6MwO2BiQ5/iMsDvufAyqnrXAGogI2ol4u2vX
CEGQQwyy22NFnOlDq4VbzHB3kycqIhCyn9X6pzpxaClwXyReZrYfzJc2r2VPTPpQ
6HXIX8JMT6DYCK9Ei74HJLuWrHPTaVXfS8vqCqggCfxaA5mQ20pSYD8Rs/3r4fEn
3qeIwzqssswqerluOArbM6NENY2H7tBuIs5RFYt3GffW0Z0FJWwCxFsdtbj9Epg+
nwIDAQAB
-----END PUBLIC KEY-----`;
